#TO DO: Create metrics for grafana using prometheus
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dms-app'
    scrape_interval: 15s
    metrics_path: /metrics
    kubernetes_sd_configs:
      - role: endpoints
    relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name]
        action: keep
        regex: default;dms-dev-app-service
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        action: keep
        regex: http
